apiVersion: v1
kind: Deployment
metadata:
 name: hello-world-deployment
spec:
 replicas: 1 
 selector:
   matchLabels:
     app: helloworldpy
 template:
   metadata:
     labels:
       app: helloworldpy
   spec:
     containers:
       - name: helloworldapp
         image: girisatapathy/hello-world
         ports:
           - containerPort: 5000
